openshift/vertical-pod-autoscaler-operator

Dockerfile
Dockerfile.rhel7

e2e is blowing up.  disable operator for now.
@joelsmith

disable operator

---

install/01_vpacontroller.crd.yaml
pkg/apis/autoscaling/v1/verticalpodautoscalercontroller_types.go
pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go
pkg/controller/verticalpodautoscaler/verticalpodautoscaler_test.go

I recommend reviewing this PR on a per-commit basis since each commit provides a different feature

Create default VPA if needed, start all 3 VPA controllers, add recommendation-only mode

---

install/05_vpa-crd.yaml

Partial fix for https://bugzilla.redhat.com/show_bug.cgi?id=1819025
See https://github.com/kubernetes/autoscaler/pull/2267 for upstream operand update.

Update CRD to match CRD in operand repo

---

pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go

Also:
- get release version from deployement object, not VPA controller object
- set pod spec defaults so that DeepEquals returns true for equivalent
pod spec templates

Bug 1819479: Only create "SuccessfulUpdate" events when updates are made

---

manifests/art.yaml

in support of https://issues.redhat.com/browse/ART-1501

Bug 1803231: art.yaml: reference files and versions that exist

---

manifests/4.5/vertical-pod-autoscaler.v4.5.0.clusterserviceversion.yaml

[release-4.5] bug 1803231: Add required CSV fields, update VPA CR example, add VPA Controller CR example

---

manifests/4.6/vertical-pod-autoscaler.v4.6.0.clusterserviceversion.yaml

See https://bugzilla.redhat.com/show_bug.cgi?id=1884413

Bug 1884413: Update manifests to pass validation and allow direct upgrades

---

manifests/4.6/vertical-pod-autoscaler.v4.6.0.clusterserviceversion.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1885213

Bug 1885213: Add support for deploymentconfigs to VPA

---

install/01_vpacontroller.crd.yaml
install/05_vpa-crd.yaml
install/06_vpacheckpoint-crd.yaml

Also split `install/06_vpacheckpoint-crd.yaml` out of `install/05_vpa-crd.yaml`

Sync OLM CRDs to manual-install CRDs

---

install/01_vpacontroller.crd.yaml
manifests/4.8/vertical-pod-autoscaler-controller.crd.yaml
manifests/4.8/vertical-pod-autoscaler.v4.8.0.clusterserviceversion.yaml
pkg/apis/autoscaling/v1/verticalpodautoscalercontroller_types.go
pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
pkg/controller/verticalpodautoscaler/updater.go
pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go

For https://issues.redhat.com/browse/OCPNODE-487

Allow control of VPA updater paramter minReplicas

---

pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go

This fixes the problem where `r.client.Get()` fails because the manager hasn't started (via it's `Start()` method). Since the reconciler interface doesn't have any initialization hook called after start, this patch uses a background goroutine to wait for the manager to start before attempting to check whether a CR exists.
This resolves the crash loop backoff with error:
```
verticalpodautoscaler_controller.go:201] Error reading VerticalPodAutoscalerController: the cache is not started, can not read objects
main.go:30] Failed to create operator: failed to add controllers: the cache is not started, can not read objects
```
This error showed up after the rebase PR #65 when we pulled in an updated controller runtime.

Fix operator start-up sequence: wait for manager start before using API client

---

Makefile

Add build target to e2e-ci targets.

---

README.md
examples/vpacontroller.yaml
install/deploy/04_vpacontroller.yaml
kustomization.yaml

Also, update example controller to use minReplicas

Use install/deploy instead of install for manifests

---

Makefile
cmd/testutil/json2yaml/json2yaml.go
cmd/testutil/yaml2json/yaml2json.go
go.mod
hack/filter-rbac.jq
hack/manifest-diff.sh
hack/yamls2list.sed
vendor/modules.txt

To run the test:
make manifest-diff

Add manifest-diff test to ensure manual-install RBAC & CRD matches OLM

---

manifests/4.10/vertical-pod-autoscaler.clusterserviceversion.yaml

Tested on ARM with e2e test suite.

Add arm64 to CSV

---

manifests/4.10/vertical-pod-autoscaler.clusterserviceversion.yaml

https://issues.redhat.com/browse/CLOUDDST-12319

Make metadata.name match art.yaml search pattern

---

.ci-operator.yaml
Makefile
hack/e2e.sh
hack/manifest-diff-upstream.sh
images/ci/bundle.Dockerfile
manifests/image-references
manifests/stable/vertical-pod-autoscaler.clusterserviceversion.yaml
manifests/vertical-pod-autoscaler.package.yaml

Ref. https://issues.redhat.com/browse/ART-5087

Bump version to 4.13

---

README.md

* remove reference to CVO / add reference to OLM
* add link to VPA product docs

Update OpenShift VPA docs

---

OWNERS

Adds team member @jkyros to owners

PODAUTO-104: Add pod autoscaling team member jkyros to VPA operator OWNERS

---

Makefile
bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
internal/operator/config.go

Needed so we can revert https://github.com/openshift-eng/ocp-build-data/pull/5741

OCPBUGS-45072: Rename operand image env var to satisfy ART build check

---

bundle/manifests/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
bundle/manifests/autoscaling.k8s.io_verticalpodautoscalers.yaml
bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml
config/vpa/vpa-crd.yaml
config/vpa/vpa-rbac.yaml
config/vpa/vpacheckpoint-crd.yaml

Copy data from `https://raw.githubusercontent.com/openshift/kubernetes-autoscaler/release-4.20/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml` to `config/vpa/vpa-crd.yaml` and `config/vpa/vpacheckpoint-crd.yaml`
Also update `config/vpa/vpa-rbac.yaml`

Update CRDs & RBAC to match operand
