Dockerfile, Dockerfile.rhel7, Makefile, install/02_vpa-rbac.yaml, install/05_vpa-crd.yaml, pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go, pkg/operator/status.go, pkg/operator/status_test.go
This reverts commit 94f9117170b3ad279a3cc72395466f8fcb2bdf64 from #3.
Also:
* check the version string at build time to make sure its format can be parsed
* add resource request to make pod burstable instead of best effort.
* fix the status check to look for the correct deployment name
=> Revert "disable operator" now that the v0.0.0 tag has been pushed

Dockerfile, Dockerfile.rhel7
Due to some gaps we uncovered with how to rollout Tech Preview operator with the CVO, we are disabling this in 4.2.  Looking to enable again in 4.3 after coordinating with CVO on design for Tech Preview operators.
@derekwaynecarr @smarterclayton @joelsmith @tkatarki @blomquisg
=> re-disable operator

OWNERS, manifests/4.4/vertical-pod-autoscaler-controller.crd.yaml, manifests/4.4/vertical-pod-autoscaler.v4.4.0.clusterserviceversion.yaml, manifests/4.4/vpa-v1.crd.yaml, manifests/4.4/vpacheckpoint-v1.crd.yaml, manifests/vertical-pod-autoscaler.package.yaml, pkg/controller/verticalpodautoscaler/admission_plugin.go, pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go
This PR contains several updates in separate commits:
1. Update RBAC to match latest operand
2. Have OLM install VPA and VPA checkpoint CRDs
* Also, make VPA controller CRD namespace instead of cluster scoped
* Also, fix OLM manfiest data, add default channel
3. Use a unique "app" label for each of the three controllers
4. Auto-obtain TLS Key/Cert for Mutating Webhook Service
To avoid having the manual step of an admin having to generate a TLS
key/cert pair for use by the Admission Controller's Mutating Webhook
Service, we needed to re-arrange a lot things:
* Have the operator create the service, complete with
annotations which the OpenShift service-ca controller
sees so that it will generate the key/cert pair and make
them available in a secret
* Have the operator create an empty …
=> Auto-obtain TLS Key/Cert for Mutating Webhook Service (+ cleanup)

install/02_vpa-rbac.yaml
... and also fix a typo in CRB name
I wasn't sure whether the required permissions in the CSV were correct, or the RBAC in the RBAC file were correct, but the RBAC was not providing sufficient permissions and OLM was rejecting installation of the operator.  If the required permissions are what is not correct I can fix those instead.
=> Fix inconsistency between RBAC and CSV required permissions

manifests/4.5/image-references
I'm pretty sure we're gonna need this; I keep finding out ways this doesn't work how I expect.
I'm testing out builds to make sure. If so, we can probably re-use bug 1803231 since it's the same problem.
=> bug 1803231: image-references: align names with RCM standards

manifests/4.5/vertical-pod-autoscaler.v4.5.0.clusterserviceversion.yaml
The last image build failed the metadation validation step. See http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-metadata-validation-test/ose-vertical-pod-autoscaler-operator-metadata-container-v4.5.0.202006031723.dev-1/ca074d41-4ded-4a5f-912a-1bfaaf6188c7/operator-metadata-linting-output.txt
This PR adds the required and recommended fields.
To validate the manifests, I did:
```
$ pip3 install operator-courier
$ operator-courier verify --ui_validate_io manifests/
```
which is what the metadata import process does as part of its tests.
=> Add required CSV fields, update VPA CR example, add VPA Controller CR example

manifests/4.5/vertical-pod-autoscaler.v4.5.0.clusterserviceversion.yaml
VPA operand rebased from upstream and picked up these changes, which cause
the updater and admission controller to fail without the updated RBAC.
https://github.com/kubernetes/autoscaler/commit/91b955316e6731f81ce8fc0c11c86db6a6300e2f#diff-d0e893b6e6e2716c431b53ecf48088b5R267
https://github.com/kubernetes/autoscaler/commit/572331a244eb30fad83e8bed7882b4756ba9d21c#diff-d0e893b6e6e2716c431b53ecf48088b5R290
=> Bug 1844760: Additional instructions for testing the VPA until official images are available

manifests/art.yaml
Having successfully pushed to stage once, tests began failing, revealing that the CSV name replacement that was supposed to happen to give it a unique name for each build - wasn't matching. So it gets the same name every time which fails the test. This should make the match work. This is required to ship.
4.6 PR is https://github.com/openshift/vertical-pod-autoscaler-operator/pull/38
=> bug 1886200: manifests/art.yaml: CSV name is verticalpodautoscaler

manifests/art.yaml
Having successfully pushed to stage once, tests began failing, revealing that the CSV name replacement that was supposed to happen to give it a unique name for each build - wasn't matching. So it gets the same name every time which fails the test. This should make the match work. This is required to ship.
=> bug 1882524: [release-4.6] manifests/art.yaml: CSV name is verticalpodautoscaler

OWNERS
This PR should get rid of the nag email from ART. From the email:
> To comply with prodsec requirements, all images in the OpenShift product should identify their Bugzilla component. To accomplish this, ART expects to find Bugzilla component information in the default branch of the image's upstream repository or requires it in ART image metadata.
=> Add bugzilla component to OWNERS file

manifests/4.6/vertical-pod-autoscaler.v4.6.0.clusterserviceversion.yaml
This version needs to change each time it's released;
without this it will stay `1.0.0` forever and fail tests.
We will need the same thing for 4.7+ (though it needs to be `4.7.0` there).
=> bug 1904260: CSV: make version match what art.yaml looks for

pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go
Updater now requires the `NAMESPACE` env var to be set so that it can make sure
the admission controller is running. Otherwise, it will emit this message in
its logs:
```
updater.go:116] Error getting Admission Controller status: leases.coordination.k8s.io "vpa-admission-controller" not found. Skipping eviction loop
```
This PR makes it so all VPA controllers set the `NAMESPACE` environment variable, where previously only the admission plugin set it.
=> Bug 1899423: Fix VPA Updater

hack/e2e.sh
1. add await_for_controllers() function in hack/e2e.sh to check if the replica status of 3 controllers change when patch verticalpodautoscalercontroller `default` with `recommendationOnly: true` set. If controllers are not created or deleted appropriately, the script will exit with 1.
2. enable both [sig-autoscaling] [VPA] [full-vpa] e2e test for `recommendationOnly: false` mode and [sig-autoscaling] [VPA] [recommender] [v1] e2e test for `recommendationOnly: true` mode. Any failed upstream e2e tests will exit with 1.
=> Add e2e tests for recommendationOnly field

Makefile, images/operator-registry/Dockerfile.registry.ci
Remove makefile image-ci target to use the default image-build macro.
Add dockerfile.ci for registry image.
=> remove image-ci target

Makefile, hack/go-fmt.sh, hack/go-lint.sh, hack/go-vet.sh, hack/yaml-lint.sh
If `NO_DOCKER=1` is set, check scripts should not try to run in a container.
Also, add `make help` text for `make clean` and `make clean-deploy`
=> Better handling of NO_DOCKER=1 in check scripts

Makefile, hack/deploy-operator-registry.sh, hack/e2e.sh, images/operator-registry/Dockerfile.registry.ci, install/olm/registry/catalog-source.yaml, install/olm/registry/registry-deployment.yaml, install/olm/registry/service.yaml, install/olm/subscription/subscription.yaml
1. Separate registry-update-binary target from build.
2. Use deployment+service+catalogsource (GRPC) way to deploy vpa-registry image in CI mode as the CI image building process cannot replace the operator and operand image on the fly.
3. Update  images/operator-registry/Dockerfile.registry.ci that will be used in the CI mode.
=> Separate build from registry-update binary build

Makefile, hack/e2e.sh
1. The e2e.sh should use ${KUBECTL} as an input variable instead of using `kubectl` for all CI tests.
2. The e2e-ci target deploy operator and controllers directly and do not need to deploy $(CONFIGMAP_ENV_FILE). Removing the configmap_env_file for registry before the deployment.
=> Pass oc to e2e.sh script for CI tests

.gitignore, install/deploy/01_vpacontroller.crd.yaml, install/deploy/05_vpa-crd.yaml, install/deploy/06_vpacheckpoint-crd.yaml, install/olm/ci-metadata/annotations.yaml, install/olm/registry/catalog-source.yaml, install/olm/registry/registry-deployment.yaml, install/olm/registry/service.yaml, manifests/4.8/vertical-pod-autoscaler-controller.crd.yaml, manifests/4.8/vpa-v1.crd.yaml, manifests/4.8/vpacheckpoint-v1.crd.yaml
The CRD API version v1beta1 is being deprecated, so we must update all CRDs to v1.
=> Bug 1950210: Update CRD API version to match upstream and cleanup for yamllint

Makefile
If the Makefile comment is correct, I believe we can ignore the semver release field after `-4` or `-gXXXXXXX`. This will make the operator less sensitive to future release naming changes.
=> Weaken VERSION check to ignore irrelevant parts of release field

install/deploy/00_namespace.yaml, install/deploy/03_deployment.yaml
According to https://bugzilla.redhat.com/show_bug.cgi?id=1805488, only components which must run before the SCC controller starts should use run-level 1. VPA is fine to run with the restricted SCC.
=> Bug 1974567: Remove unneeded run-level from namespace in manual install manifests

go.mod, go.sum, vendor/modules.txt
rebase work for vpa operator https://issues.redhat.com/browse/OCPNODE-535
Signed-off-by: Qi Wang <qiwan@redhat.com>
=> update the go.mod by go mod tidy

manifests/4.9/vertical-pod-autoscaler.v4.9.0.clusterserviceversion.yaml
I was using the single quotes instead of double quotes by mistake, which didn't interpret backslash as a line continuation. Before:
```
yaml2json manifests/4.9/vertical-pod-autoscaler.v4.9.0.clusterserviceversion.yaml | jq -r .spec.icon[0].base64data
\ PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTI\ gMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PH\ BhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuN\ TMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEs\ NDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTI …
```
=> Bug 1999168: Fix VPA's icon in OperatorHub

install/deploy/02_vpa-rbac.yaml, manifests/4.9/vertical-pod-autoscaler.v4.9.0.clusterserviceversion.yaml
From upstream kubernetes/autoscaler/pull/3139
=> Bug 1999951: Allow VPA to read scale subresource of any object

manifests/4.9/vertical-pod-autoscaler.v4.9.0.clusterserviceversion.yaml
The OperatorHub currently assumes x86-only for any operators which do
not declare any such labels.  Declaring these explicitly should make the
current status more obvious in the code, and make it easier to correctly
add further architectures when conditions warrant.
=> Bug 1987136: Declare supported arches in CSV

hack/e2e.sh, test/registry-setup/main.go
Also, make E2E tests a little more robust by waiting for cluster to reach the expected state after toggling between `recommendationOnly: true` and `false`.
Depends upon https://github.com/openshift/release/pull/22160
=> Update CI test to use CI dep images instead of IMAGE_FORMAT

manifests/4.10/vertical-pod-autoscaler.clusterserviceversion.yaml
Per [MULTIARCH-1517](https://issues.redhat.com/browse/MULTIARCH-1517) / [MULTIARCH-646](https://issues.redhat.com/browse/MULTIARCH-646)
Delivering VPA operator for ppc64le and s390x. The multi-arch team tested the 5 uses of VPA detailed here: https://docs.openshift.com/container-platform/4.9/nodes/pods/nodes-pods-vertical-autoscaler.html#nodes-pods-vertical-autoscaler-using-about_nodes-pods-vertical-autoscaler as well as e2e tests, on ppc64le and s390x
=> MULTIARCH-1517: Add support label for ppc64le and s390x

hack/e2e.sh, manifests/vertical-pod-autoscaler.package.yaml
The manifest change only affects a manual build or the builds used for E2E tests. Customer-facing builds use generated manifests and are not affected by this change.
Also, the upstream E2E tests were broken for 4.10 since this fix PR did not merge prior to our upstream rebase for 4.10: https://github.com/kubernetes/autoscaler/pull/4771
So this fix will use the 4.9 code only for the E2E tests (not for anything else).
=> [release-4.10] OCPBUGS-2662: Fix E2E CI tests by making currentCSV match CSV file

Makefile, hack/filter-upstream-rbac.jq, hack/manifest-diff-upstream.sh, hack/manifest-diff.sh, install/deploy/06_vpacheckpoint-crd.yaml, manifests/stable/vpacheckpoint-v1.crd.yaml
Currently we have no check to detect when a change is made to the upstream VPA which requires a manifest change to the VPA operator. This PR seeks to remedy that deficiency. This new check will fetch 2 key manifests from the OpenShift fork of the Kubernetes Autoscaling repo: The RBAC objects and the CRD objects.
The check detected that we were missing the status stanza of the VPA Checkpoint CRD, so this PR also adds that stanza so that this PR can pass.
=> Add manifest-diff-upstream to help keep VPA Operator manifests in sync with the VPA operand

Makefile, install/deploy/01_vpacontroller.crd.yaml, manifests/stable/vertical-pod-autoscaler-controller.crd.yaml, pkg/apis/autoscaling/v1/verticalpodautoscalercontroller_types.go, pkg/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go, pkg/controller/verticalpodautoscaler/verticalpodautoscaler_test.go
Also, clean up TestOverrideResources's flipped expected/actual ordering
=> PODAUTO-102: Add NodeSelector and Tolerations fields to deploymentoverrides

Dockerfile.rhel7
- We run our builds in a disconnected environment 
- `go mod verify`  tries to connect to the internet to check modules hashes
- that doesn't work in our disconnected environment: 
```2024-08-29 07:08:17,246 - atomic_reactor.tasks.binary_container_build - INFO - go: github.com/beorn7/perks@v1.0.1: Get "https://proxy.golang.org/github.com/beorn7/perks/@v/v1.0.1.mod": Forbidden``` (that's just the first module, it starts at the beginning) 
This PR just removes `go mod verify` to unblock builds. 
Today I learned :smile:
=> PODAUTO-225: Remove go mod verify from Dockerfile

Makefile, bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml, config/samples/kustomization.yaml
This commit re-enables the VPA example in the CSV for the OCP console to use. Turns out the VPA is a "supported resource" and operator-sdk adds your supported resource examples to the bundle regardless if it's actually an owned resource or not. This commit simply uncomments the sample, and manually removes it from the bundle folder after we generate the bundle. 
This is what I am talking about: https://github.com/operator-framework/operator-registry/blob/c8307cac2e6ea71b3719e6d5a5850dd639da296f/pkg/lib/bundle/supported_resources.go#L18
Operator-sdk generate bundle goes through files and writes [CRDs, Services, and "supported resources"](https://github.com/operator-framework/operator-sdk/blob/819984d4c1a51c8ff2ef6c23944554148ace0752/internal/cmd/operator-sdk/generate/internal/manifests.go#L …
=> PODAUTO-225: Re-enable VPA alm-example in CSV and add spec descriptors

bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml
OCP puts in `skips`. There is no need for `replaces`, and this make a release pipeline hurt, see e.g. https://iib.engineering.redhat.com/api/v1/builds/874123/logs
=> Remove replaces from manifest

Makefile, bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml, internal/controller/verticalpodautoscaler/admission_plugin.go, internal/controller/verticalpodautoscaler/verticalpodautoscaler_controller.go, internal/controller/verticalpodautoscaler/verticalpodautoscaler_controller_test.go, internal/util/util.go, internal/util/util_test.go
Updates defaults according to vpa benchmarking spike/new documentation defaults.
I was thinking of not setting CPU limits for the operator, but since we [_should ideally_](https://sdk.operatorframework.io/docs/best-practices/managing-resources/#managing-resources) set memory limits at least, I added additional CPU limits to the main container (alongisde the kube-rbac-proxy container limits), in case something _really_ goes wrong somehow, we do not use more CPU than intended (and all the operator is doing is reconciling anyways).
=> OCPBUGS-45372: Update default resource requests and QPS/Burst

Makefile
Add ensure-commands-are-noops ci check such that we make sure that a dev has run make bundle and make generate before pushing their changes.
~Also removes gofmt and govet make targets since golangci-lint already has rules that do the same thing~, and fixes up `make check` such that it includes all commands that devs can and should use before pushing.
=> PODAUTO-284: Add CI checks to ensure "make bundle/generate" before pushing 

Makefile, bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml, config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml, config/olm-catalog/vpa-subscription.yaml
Removes the annotation because the operator code itself initializes a VPA controller object during startup.
Also fix incorrect package name in local catalogsource manifest and make sure namespace is regenerated before deploying during local testing.
=> OCPBUGS-45521: Remove unnecessary initialization-resource CSV annotation

Makefile
This is a follow-up to #197
Un-owned files from previous versions were being left around in the bundle without manually removing the bundle/manifests dir prior to regenerating.
=> Clean old bundles before regenerating

Makefile, bundle/image-references, bundle/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml, bundle/vertical-pod-autoscaler-operator.package.yaml, config/manager/kustomization.yaml, config/manifests/bases/vertical-pod-autoscaler.clusterserviceversion.yaml, config/olm-catalog/vpa-catalogsource.yaml, hack/e2e.sh, hack/manifest-diff-upstream.sh
```
sed -i 's/4.19/4.20/g' $(git grep -l 4.19 config/) hack/manifest-diff-upstream.sh hack/e2e.sh Makefile bundle/image-references bundle/vertical-pod-autoscaler-operator.package.yaml
```
This commit updates references in the repo from 4.19 to 4.20, except for actually bumping go dependencies. We need this to satisfy ART builds, but we cannot do a full update for our OpenShift 4.20 dependencices yet due to the k8s 1.33 rebase not being finished, so we will hold off on golang dep bumps, go1.24 bumps, and image bumps until then.
We will have a separate PR for that once the rebase resolves.
=> OCPBUGS-57966: Updates for 4.20
